apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.service.name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Values.service.name }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: health
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service.name }}
